
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const LegalDisclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 relative">
      <div className="absolute inset-0 bg-cyber-dark-blue/50" />
      
      <div className="container mx-auto px-4 relative z-10">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="inline-flex items-center gap-2 font-cyber text-sm text-cyber-orange">
              <AlertTriangle size={16} />
              <span>Important Information</span>
            </span>
            <h2 className="text-4xl font-bold mt-2 mb-6 font-news">Legal Disclaimer</h2>
          </div>
          
          <div className="cyber-card border-cyber-orange/30">
            <Shield className="text-cyber-orange mx-auto mb-6" size={32} />
            
            <div className="space-y-6 text-cyber-gray">
              <p>
                <strong className="text-white">Educational Purpose:</strong> Historical Headlines GPT is designed for educational, research, and entertainment purposes only. While we strive for historical accuracy, the content generated should not be considered a primary historical source or used for academic citations.
              </p>
              
              <p>
                <strong className="text-white">Historical Perspective:</strong> Articles generated by Historical Headlines GPT may reflect the biases, limitations, and prevailing views of the time periods they represent. These perspectives may include outdated, offensive, or harmful language and viewpoints that do not align with modern values. The inclusion of such perspectives is meant to accurately represent historical contexts and should not be interpreted as endorsement.
              </p>
              
              <p>
                <strong className="text-white">Content Accuracy:</strong> AI Web Tools LLC makes no guarantees regarding the complete accuracy of all historical details in generated content. Users should verify important historical information through reputable historical sources.
              </p>
              
              <p>
                <strong className="text-white">Third-Party Integration:</strong> Historical Headlines GPT utilizes OpenAI's technology. By using this tool, you agree to comply with OpenAI's terms of service and policies. AI Web Tools LLC is not responsible for changes or limitations imposed by OpenAI that may affect this tool's functionality.
              </p>
              
              <p>
                <strong className="text-white">Use Restrictions:</strong> Users agree not to use Historical Headlines GPT to:
              </p>
              <ul className="list-disc pl-8 space-y-1">
                <li>Generate deliberately misleading historical content</li>
                <li>Create content that promotes hatred, discrimination, or violence</li>
                <li>Produce content that could be harmful to individuals or groups</li>
                <li>Impersonate historical figures or entities in a deceptive manner</li>
              </ul>
              
              <p>
                <strong className="text-white">Liability Limitation:</strong> AI Web Tools LLC and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your use of, or inability to use, Historical Headlines GPT.
              </p>
              
              <p>
                <strong className="text-white">Copyright and Attribution:</strong> Content generated by Historical Headlines GPT is provided for personal use. For public sharing or publication of generated content, proper attribution to "Historical Headlines GPT by AI Web Tools" is required, along with a clear indication that the content was AI-generated.
              </p>
              
              <p>
                By using Historical Headlines GPT, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. AI Web Tools LLC reserves the right to modify these terms at any time without prior notice.
              </p>
            </div>
            
            <div className="mt-8 pt-8 border-t border-cyber-orange/30 text-center text-sm text-cyber-gray">
              <p>For questions about this disclaimer, please contact:</p>
              <div className="mt-2">
                <a href="tel:+14758008096" className="text-cyber-blue hover:text-cyber-blue-dark transition-colors">
                  (475) 800-8096
                </a>
                <span className="mx-2">|</span>
                <a href="mailto:Contact@ai-webtools.com" className="text-cyber-blue hover:text-cyber-blue-dark transition-colors">
                  Contact@ai-webtools.com
                </a>
              </div>
            </div>
          </div>
          
          <div className="mt-8 text-center">
            <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-cyber-blue hover:text-cyber-blue-dark mr-6 transition-colors text-sm">
              Privacy Policy
            </a>
            <a href="https://aiwebtools.ai/terms-of-services" target="_blank" rel="noopener noreferrer" className="text-cyber-blue hover:text-cyber-blue-dark transition-colors text-sm">
              Terms of Service
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalDisclaimer;
